name: Build and Test

on:
  pull_request:
  push:
    branches:
      - main
      - releases/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: actions/checkout@v3
      - run: npm i
      - run: npm run build

      - uses: ./
        with:
          # 在这个地方放需要拿出来的GitHub Action Secrets
          input_values: |
            - ${{ secrets.GH_ACCESS_TOKEN }}
